train_cfg:
  root: "/media/jiao/KESU/dataset/DFDC/dfdc_test"
  split: "train"
  log_steps: 1000
  val_steps: 1000
  num_steps: 100000
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "HorizontalFlip"
      params:
        p: 0.5
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
test_cfg:
  root: "/media/jiao/KESU/dataset/DFDC/dfdc_test"
  split: "test"
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]