train_cfg:
  root: "/media/jiao/KESU/dataset/WildDeepfake"
  split: "train"
  num_image_train:
  log_steps: 200
  val_steps: 200
  num_steps: 30000
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "HorizontalFlip"
      params:
        p: 0.5
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
test_cfg:
  root: "/media/jiao/KESU/dataset/WildDeepfake"
  split: "test"
  num_image_test:  30000
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]